In [21]:
import numpy as np
import scipy.stats as stats

In [22]:
# Observed frequencies from the contingency table
observed = np.array([
    [50, 70],
    [80, 100],
    [60, 90],
    [30, 50],
    [20, 50]
])

# Row and column totals
row_total = observed.sum(axis=1)
col_total = observed.sum(axis=0)
total = observed.sum()

In [23]:
row_total

array([120, 180, 150,  80,  70])

In [24]:
col_total

array([240, 360])

In [25]:
total

600

In [26]:
# Compute expected frequencies
expected = np.outer(row_totals, col_totals) / total
expected

array([[ 48.,  72.],
       [ 72., 108.],
       [ 60.,  90.],
       [ 32.,  48.],
       [ 28.,  42.]])

In [27]:
# Calculate the Chi-Square statistic
chi_square_stat = ((observed - expected)**2 / expected).sum()
chi_square_stat

5.638227513227513

In [28]:
# Degrees of freedom
df = (observed.shape[0] - 1) * (observed.shape[1] - 1)
df

4

In [29]:
# Critical value for alpha = 0.05
alpha = 0.05
critical_value = stats.chi2.ppf(1 - alpha, df)
critical_value

9.487729036781154

In [30]:
# p-value
p_value = 1 - stats.chi2.cdf(chi_square_stat, df)
p_value

0.22784371130697179

In [31]:

# Decision
if chi_square_stat > critical_value:
    decision = "Reject the null hypothesis (H0)"
else:
    decision = "Fail to reject the null hypothesis (H0)"
decision

'Fail to reject the null hypothesis (H0). There is no significant association.'